export default {
  type: "excalidraw",
  version: 2,
  source: "https://excalidraw.com",
  elements: [
    {
      id: "EOsD1SyghcPh7qzlD9k24",
      type: "rectangle",
      x: 354,
      y: 199,
      width: 270,
      height: 140,
      angle: 0,
      strokeColor: "#000000",
      backgroundColor: "#228be6",
      fillStyle: "solid",
      strokeWidth: 4,
      strokeStyle: "solid",
      roughness: 2,
      opacity: 100,
      groupIds: [],
      roundness: {
        type: 3,
      },
      seed: 1834694554,
      version: 94,
      versionNonce: 650088774,
      isDeleted: false,
      boundElements: null,
      updated: 1674249589669,
      link: null,
      locked: false,
    },
    {
      id: "scGZlyivDfCDDHYEV9cbW",
      type: "text",
      x: 381,
      y: 241,
      width: 412,
      height: 60,
      angle: 0,
      strokeColor: "#000000",
      backgroundColor: "transparent",
      fillStyle: "hachure",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      groupIds: [],
      roundness: null,
      seed: 468398470,
      version: 218,
      versionNonce: 1446905222,
      isDeleted: false,
      boundElements: null,
      updated: 1674249602665,
      link: null,
      locked: false,
      text: "mit Biss!",
      fontSize: 46.923076923076884,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "top",
      baseline: 42,
      containerId: null,
      originalText: "Ein Kurs mit Biss!",
    },
  ],
  appState: {
    gridSize: null,
    viewBackgroundColor: "#ffffff",
  },
  files: {},
  scrollToContent: true,
};
